name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  # - requests=2.31.0
  # - pip=20.3.3
  # - mlflow=1.14.1
  # - hydra-core=1.3.2
  # - pip:
  #     - wandb==0.16.2
  - python=3.8
  - numpy==1.23.4
  - pandas=1.2.3
  - scikit-learn=0.24.1
  - mlflow=1.14.1
  - matplotlib==3.2.2
  - plotly==4.4.1
  - pillow=8.1.2
  - pip=23.3.1
  - pip:
      - wandb==0.16.2
      - hydra-joblib-launcher==1.1.2